version: '2.2'

services:
  openhab:
    image: "openhab/openhab:snapshot-debian"
    container_name: "synology_openhab_openhab3"
    restart: always
    network_mode: bridge
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/TZ:/etc/timezone:ro"
      - "/volume1/docker/openhab/addons:/openhab/addons"
      - "/volume1/docker/openhab/conf:/openhab/conf"
      - "/volume1/docker/openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Asia/Singapore"
  frontail:
    image: welteki/frontail-openhab
    container_name: synology_openhab_frontail
    restart: always
    network_mode: bridge
    ports:
      - "9001:9001"
    volumes:
      - /volume1/docker/openhab/userdata:/openhab/userdata
volumes:
  userdata:
